-- Add NotificationType enum and new fields (type, entityId, link) to Notification
CREATE TYPE "NotificationType" AS ENUM (
  'PROPOSAL_SENT',
  'PROPOSAL_ACCEPTED',
  'PROPOSAL_REJECTED',
  'PROPOSAL_EXPIRED',
  'APPROVAL_REQUESTED',
  'APPROVAL_ACCEPTED',
  'APPROVAL_REJECTED',
  'INVOICE_SENT',
  'INVOICE_OVERDUE',
  'PAYMENT_RECEIVED',
  'PROJECT_STATUS_CHANGED',
  'TASK_ASSIGNED',
  'SERVICE_REQUEST_CREATED',
  'SERVICE_REQUEST_STATUS_CHANGED',
  'SERVICE_REQUEST_COMMENT',
  'BRIEF_COMPLETED',
  'DOCUMENT_SIGNED',
  'LEAD_CONVERTED',
  'FREELANCER_APPLICATION',
  'GENERAL'
);

ALTER TABLE "Notification"
  ADD COLUMN "type"     "NotificationType" NOT NULL DEFAULT 'GENERAL',
  ADD COLUMN "entityId" VARCHAR(255),
  ADD COLUMN "link"     VARCHAR(500);
