import { z } from "zod";
import {
  invoiceItemSchema,
  createCreditNoteSchema as creditNoteSchema,
  addPaymentSchema as sharedAddPaymentSchema,
  currencyCode,
  positiveDecimal,
} from "@secritou/shared";

const uuidParam = z.string().uuid();

export const createInvoiceSchema = z.object({
  body: z.object({
    // RG-012: number is always generated by nextInvoiceNumber (InvoiceCounter, sequential,
    // gapless per month) — never accepted from the client, which could bypass the counter
    // entirely and break the sequence's continuity guarantee (SEC-031). This is why the server
    // schema below does not simply import shared's invoiceBaseSchema wholesale: that schema
    // includes a required `number` field meant for a different (non-API) consumer.
    title: z.string().min(1).max(255),
    description: z.string().max(5000).optional(),
    amount: positiveDecimal,
    // RG-001: every proposal/invoice is denominated in TND — no other currency is accepted in
    // writing (SEC-032). Not just a default: a caller-supplied non-TND value must be rejected,
    // since analytics/forecast repositories already filter on DEFAULT_CURRENCY and would silently
    // exclude any other-currency invoice from every financial KPI.
    currency: currencyCode.default("TND"),
    clientId: z.string().uuid(),
    projectId: z.string().uuid().optional(),
    dueDate: z.string().datetime({ offset: true }).optional(),
    items: z.array(invoiceItemSchema).optional(),
  }),
});

export const updateInvoiceSchema = z.object({
  params: z.object({ id: uuidParam }),
  body: z.object({
    title: z.string().min(1).max(255).optional(),
    description: z.string().max(5000).optional(),
    amount: positiveDecimal.optional(),
    currency: currencyCode.optional(),
    dueDate: z.string().datetime({ offset: true }).optional().nullable(),
  }),
});

export const invoiceIdParamSchema = z.object({
  params: z.object({ id: uuidParam }),
});

export const setReminderPausedSchema = z.object({
  params: z.object({ id: uuidParam }),
  body: z.object({
    reminderPaused: z.boolean(),
  }),
});

export const addPaymentSchema = z.object({
  params: z.object({ id: uuidParam }),
  // Extends shared's addPaymentSchema with idempotencyKey — a server-only concurrency concern
  // the client never sets directly, so it's not part of the shared client/server contract.
  body: sharedAddPaymentSchema.extend({
    idempotencyKey: z.string().max(255).optional(),
  }),
});

export const addReminderSchema = z.object({
  params: z.object({ id: uuidParam }),
  body: z.object({
    type: z.string().min(1).max(100),
  }),
});

export const addInvoiceItemSchema = z.object({
  params: z.object({ id: uuidParam }),
  body: invoiceItemSchema,
});

export const updateInvoiceItemSchema = z.object({
  params: z.object({ id: uuidParam, itemId: uuidParam }),
  body: invoiceItemSchema.partial(),
});

export const invoiceItemParamSchema = z.object({
  params: z.object({ id: uuidParam, itemId: uuidParam }),
});

export const createCreditNoteSchema = z.object({
  params: z.object({ id: uuidParam }),
  body: creditNoteSchema,
});

export const applyCreditSchema = z.object({
  params: z.object({ id: uuidParam }),
  body: z.object({
    creditNoteId: z.string().uuid(),
  }),
});

export const fromTimeEntriesSchema = z.object({
  params: z.object({ id: uuidParam }),
  body: z.object({
    projectId: z.string().uuid(),
    defaultHourlyRate: z.number().positive().default(50),
  }),
});
