import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().default(5000),
  DATABASE_URL: z.string().url(),
  DATABASE_READ_URL: z.string().url().optional(),
  JWT_ACCESS_SECRET: z.string().min(32),
  JWT_REFRESH_SECRET: z.string().min(32),
  JWT_ISSUER: z.string().default("secritou-api"),
  JWT_AUDIENCE: z.string().default("secritou-web"),
  JWT_ACCESS_EXPIRES_IN: z.string().default("15m"),
  JWT_REFRESH_EXPIRES_IN: z.string().default("7d"),
  REFRESH_COOKIE_NAME: z.string().default("secritou_refresh"),
  FRONTEND_URL: z.string().url().default("http://localhost:5173"),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().optional(),
  SMTP_USER: z.string().optional(),
  SMTP_PASSWORD: z.string().optional(),
  CONTACT_RECEIVER_EMAIL: z.string().email().default("contact@secritou.tn"),
  ADMIN_NOTIFICATION_EMAIL: z.string().email().default("contact@secritou.tn"),
  // Company that owns leads generated by the public website contact form.
  // Defaults to the seeded internal agency company.
  INTERNAL_COMPANY_ID: z.string().default("seed-company-001"),
  OPENAI_API_KEY: z.string().optional(),
  METRICS_ENABLED: z
    .string()
    .optional()
    .transform((v) => v !== "false" && v !== "0"),
  METRICS_PATH: z.string().default("/metrics"),
  METRICS_TOKEN: z.string().optional(),
  REDIS_URL: z.string().optional(),
  REDIS_HOST: z.string().optional(),
  REDIS_PORT: z.coerce.number().optional(),
  REDIS_USERNAME: z.string().optional(),
  REDIS_PASSWORD: z.string().optional(),
  REDIS_DB: z.coerce.number().optional(),
  CACHE_ENABLED: z
    .string()
    .optional()
    .transform((v) => v === "true" || v === "1"),
  JOBS_ENABLED: z
    .string()
    .optional()
    .transform((v) => v !== "false" && v !== "0"),
  S3_REGION: z.string().default("us-east-1"),
  S3_BUCKET: z.string().optional(),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
  S3_ENDPOINT: z.string().url().optional(),
  S3_PUBLIC_URL: z.string().url().optional(),
  S3_PUBLIC_ACL: z
    .string()
    .optional()
    .transform((v) => v === "true"),
  UPLOAD_MAX_BYTES: z.coerce.number().default(20 * 1024 * 1024),
  SENTRY_DSN: z.string().url().optional(),
  OLLAMA_URL: z.string().url().default("http://localhost:11434"),
  OLLAMA_MODEL: z.string().default("mistral"),
  // Google OAuth (Search Console connector). Redirect URI must be registered
  // exactly as-is in the Google Cloud OAuth client's "Authorized redirect URIs".
  GOOGLE_OAUTH_CLIENT_ID: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_SECRET: z.string().optional(),
  GOOGLE_OAUTH_REDIRECT_URI: z.string().url().optional(),
  // 32-byte key (base64 or hex) used to encrypt OAuth refresh tokens at rest (AES-256-GCM).
  INTEGRATIONS_ENCRYPTION_KEY: z.string().optional(),
  // Revenue forecast: coarse win-probability by proposal status (0-1). Defaults are guesses
  // made before any real mission data existed — recalibrate once there's a track record.
  FORECAST_PROBABILITY_SENT: z.coerce.number().min(0).max(1).default(0.2),
  FORECAST_PROBABILITY_VIEWED: z.coerce.number().min(0).max(1).default(0.4),
  // Executive metrics: an invoice this many days past due marks its client "at risk".
  FORECAST_AT_RISK_DAYS: z.coerce.number().int().positive().default(30),
  // Recurring meeting reminder: notify this many days before Project.nextMeetingDate.
  MEETING_REMINDER_DAYS: z.coerce.number().int().positive().default(3),
});

export const env = envSchema.parse(process.env);

const KNOWN_PLACEHOLDER_SECRETS = new Set([
  "your-super-secret-jwt-key-min-32-chars",
  "your-super-secret-refresh-key-min-32-chars",
]);

if (
  env.NODE_ENV === "production" &&
  (KNOWN_PLACEHOLDER_SECRETS.has(env.JWT_ACCESS_SECRET) ||
    KNOWN_PLACEHOLDER_SECRETS.has(env.JWT_REFRESH_SECRET))
) {
  throw new Error(
    "JWT_ACCESS_SECRET/JWT_REFRESH_SECRET are set to known placeholder values. Generate unique secrets before running in production."
  );
}

// Google OAuth (Search Console) is considered "enabled" once its client credentials are set.
// If so, INTEGRATIONS_ENCRYPTION_KEY must be present and decode to exactly 32 bytes — otherwise
// every GSC connection attempt would fail at runtime with a 500 (see utils/encryption.ts and
// gscConnection.service.ts, which both re-check this lazily on each call). Fail at boot instead.
const googleOAuthConfigured = Boolean(
  env.GOOGLE_OAUTH_CLIENT_ID && env.GOOGLE_OAUTH_CLIENT_SECRET && env.GOOGLE_OAUTH_REDIRECT_URI
);
if (googleOAuthConfigured) {
  if (!env.INTEGRATIONS_ENCRYPTION_KEY) {
    throw new Error(
      "GOOGLE_OAUTH_CLIENT_ID/SECRET/REDIRECT_URI are set but INTEGRATIONS_ENCRYPTION_KEY is missing. " +
      "Set INTEGRATIONS_ENCRYPTION_KEY (32 bytes, base64 or hex) before starting the server."
    );
  }
  const raw = env.INTEGRATIONS_ENCRYPTION_KEY;
  const keyLength = /^[0-9a-fA-F]{64}$/.test(raw)
    ? Buffer.from(raw, "hex").length
    : Buffer.from(raw, "base64").length;
  if (keyLength !== 32) {
    throw new Error(
      "INTEGRATIONS_ENCRYPTION_KEY must decode to exactly 32 bytes (base64 or hex) — Google OAuth is configured, so this key is required."
    );
  }
}
