import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().default(5000),
  DATABASE_URL: z.string().url(),
  DATABASE_READ_URL: z.string().url().optional(),
  JWT_ACCESS_SECRET: z.string().min(32),
  JWT_REFRESH_SECRET: z.string().min(32),
  JWT_ISSUER: z.string().default("secritou-api"),
  JWT_AUDIENCE: z.string().default("secritou-web"),
  JWT_ACCESS_EXPIRES_IN: z.string().default("15m"),
  JWT_REFRESH_EXPIRES_IN: z.string().default("7d"),
  REFRESH_COOKIE_NAME: z.string().default("secritou_refresh"),
  FRONTEND_URL: z.string().url().default("http://localhost:5173"),
  // Public base URL of this API — used to build callback URLs for external services (n8n
  // workflows calling back into Secritou). Defaults to local dev; must be set explicitly in
  // any deployed environment since the server can't know its own public hostname.
  API_URL: z.string().url().default("http://localhost:5000"),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().optional(),
  SMTP_USER: z.string().optional(),
  SMTP_PASSWORD: z.string().optional(),
  CONTACT_RECEIVER_EMAIL: z.string().email().default("contact@secritou.tn"),
  ADMIN_NOTIFICATION_EMAIL: z.string().email().default("contact@secritou.tn"),
  // Company that owns leads generated by the public website contact form.
  // Defaults to the seeded internal agency company.
  INTERNAL_COMPANY_ID: z.string().default("seed-company-001"),
  OPENAI_API_KEY: z.string().optional(),
  METRICS_ENABLED: z
    .string()
    .optional()
    .transform((v) => v !== "false" && v !== "0"),
  METRICS_PATH: z.string().default("/metrics"),
  METRICS_TOKEN: z.string().optional(),
  REDIS_URL: z.string().optional(),
  REDIS_HOST: z.string().optional(),
  REDIS_PORT: z.coerce.number().optional(),
  REDIS_USERNAME: z.string().optional(),
  REDIS_PASSWORD: z.string().optional(),
  REDIS_DB: z.coerce.number().optional(),
  CACHE_ENABLED: z
    .string()
    .optional()
    .transform((v) => v === "true" || v === "1"),
  // Set only by .github/workflows/ci.yml's e2e job's "Start server" step — a full e2e run
  // sequentially fires far more sensitive-write calls (proposal create/send/accept, invoice
  // send/pay, project status updates) across several spec files than any single real user would
  // in the same window, tripping sensitiveWriteRateLimit (10/min) well before the suite finishes.
  // Never set in a real deployment or in local `npm run dev` — this widens a real security
  // control, so it must be an explicit, narrow opt-in, not inferred from NODE_ENV=development
  // (which e2e also runs under, but so does every local dev server).
  E2E_RELAXED_RATE_LIMITS: z
    .string()
    .optional()
    .transform((v) => v === "true" || v === "1"),
  // SEC-102: set only by .github/workflows/ci.yml's "server" job (npm run test:coverage) — that
  // suite's .http.test.ts files accumulate 24+ real /auth/login calls sharing authRateLimit's one
  // in-memory 30/15min counter, eventually 429ing a later, unrelated test as more HTTP test files
  // are added. Deliberately separate from E2E_RELAXED_RATE_LIMITS: that flag also widens
  // sensitiveWriteRateLimit/frequentInteractionRateLimit, which taskUpdateRateLimit.test.ts
  // asserts stay at their real limits during this exact job — widening those too would break that
  // test's own proof. Never set in a real deployment or in local `npm run dev`.
  E2E_RELAXED_AUTH_RATE_LIMIT: z
    .string()
    .optional()
    .transform((v) => v === "true" || v === "1"),
  JOBS_ENABLED: z
    .string()
    .optional()
    .transform((v) => v !== "false" && v !== "0"),
  S3_REGION: z.string().default("us-east-1"),
  S3_BUCKET: z.string().optional(),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
  S3_ENDPOINT: z.string().url().optional(),
  S3_PUBLIC_URL: z.string().url().optional(),
  S3_PUBLIC_ACL: z
    .string()
    .optional()
    .transform((v) => v === "true"),
  UPLOAD_MAX_BYTES: z.coerce.number().default(20 * 1024 * 1024),
  SENTRY_DSN: z.string().url().optional(),
  OLLAMA_URL: z.string().url().default("http://localhost:11434"),
  // qwen2.5:3b-instruct chosen over mistral (7B) after live comparison on CPU-only hardware
  // (Ryzen 7 5800HS, 16 Go RAM) using the project's real tool schemas (session du 2026-08-01) :
  // mistral occasionally returned a raw JSON tool call inside `content` instead of the structured
  // `tool_calls` field callOllamaWithTools actually parses, and once spent 114s emitting all 4
  // tool signatures as prose instead of answering a plain "Bonjour" — qwen2.5:3b answered the same
  // greeting correctly in ~2.6s with zero false-positive tool calls, and was ~4-5x faster warm on
  // tool-calling turns (also compared against llama3.2:3b, which called getAgencyOverview() on
  // every single "Bonjour" in 3/3 runs — a deterministic false positive, not a fluke). mistral
  // stays documented as a fallback in server/.env.example if a future model swap regresses
  // tool-calling reliability.
  OLLAMA_MODEL: z.string().default("qwen2.5:3b-instruct"),
  // Context window (tokens) requested from Ollama for each /api/chat call. Conversation history is
  // already capped at the last 20 messages (aiConversation.service.ts), and the turn additionally
  // carries SYSTEM_PROMPT + up to 13 tool definitions — 4096 leaves headroom for that combination
  // on CPU-only hosts without over-allocating RAM for context the module never actually uses.
  OLLAMA_NUM_CTX: z.coerce.number().int().positive().default(4096),
  // Max tokens Ollama will generate per reply. SYSTEM_PROMPT asks for concise replies — this caps
  // worst-case CPU generation time per turn rather than relying on the model to self-limit length.
  OLLAMA_NUM_PREDICT: z.coerce.number().int().positive().default(512),
  // SEC-070: semantic search (RAG, pgvector) — a separate embedding model from OLLAMA_MODEL above.
  // nomic-embed-text produces 768-dimension vectors (SearchEmbedding.embedding, schema.prisma) —
  // swapping this without also migrating the schema's vector(768) dimension would break every
  // already-stored embedding.
  OLLAMA_EMBEDDING_MODEL: z.string().default("nomic-embed-text"),
  // Google OAuth (Search Console connector). Redirect URI must be registered
  // exactly as-is in the Google Cloud OAuth client's "Authorized redirect URIs".
  GOOGLE_OAUTH_CLIENT_ID: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_SECRET: z.string().optional(),
  GOOGLE_OAUTH_REDIRECT_URI: z.string().url().optional(),
  // 32-byte key (base64 or hex) used to encrypt OAuth refresh tokens at rest (AES-256-GCM).
  INTEGRATIONS_ENCRYPTION_KEY: z.string().optional(),
  // Revenue forecast: coarse win-probability by proposal status (0-1). Defaults are guesses
  // made before any real mission data existed — recalibrate once there's a track record.
  FORECAST_PROBABILITY_SENT: z.coerce.number().min(0).max(1).default(0.2),
  FORECAST_PROBABILITY_VIEWED: z.coerce.number().min(0).max(1).default(0.4),
  // Executive metrics: an invoice this many days past due marks its client "at risk".
  FORECAST_AT_RISK_DAYS: z.coerce.number().int().positive().default(30),
  // Recurring meeting reminder: notify this many days before Project.nextMeetingDate.
  MEETING_REMINDER_DAYS: z.coerce.number().int().positive().default(3),
  // GSC anomaly detection: flag a client's daily clicks as anomalous when they deviate from
  // the trailing 7-day average by at least this percentage (0-1, e.g. 0.5 = 50%).
  GSC_ANOMALY_THRESHOLD_PCT: z.coerce.number().min(0).max(1).default(0.5),
  // SLA thresholds for n8n escalation hooks: an OPEN custom question with no staff reply, or
  // a PENDING approval, older than this is flagged so an external channel (Slack, etc.) can
  // surface it — separate from the in-app notifications already created when these are raised.
  CUSTOM_QUESTION_SLA_HOURS: z.coerce.number().int().positive().default(24),
  APPROVAL_SLA_DAYS: z.coerce.number().int().positive().default(3),
  // n8n integration: outbound webhooks for events n8n workflows react to (Slack/Teams
  // notifications, LLM-enriched reports, etc). Feature is "enabled" only when both are set —
  // see the boot check below, mirroring the Google OAuth pattern.
  N8N_WEBHOOK_BASE_URL: z.string().url().optional(),
  N8N_WEBHOOK_SECRET: z.string().min(16).optional(),
});

export const env = envSchema.parse(process.env);

const KNOWN_PLACEHOLDER_SECRETS = new Set([
  "your-super-secret-jwt-key-min-32-chars",
  "your-super-secret-refresh-key-min-32-chars",
]);

if (
  env.NODE_ENV === "production" &&
  (KNOWN_PLACEHOLDER_SECRETS.has(env.JWT_ACCESS_SECRET) ||
    KNOWN_PLACEHOLDER_SECRETS.has(env.JWT_REFRESH_SECRET))
) {
  throw new Error(
    "JWT_ACCESS_SECRET/JWT_REFRESH_SECRET are set to known placeholder values. Generate unique secrets before running in production."
  );
}

if (env.NODE_ENV === "production" && env.E2E_RELAXED_RATE_LIMITS) {
  throw new Error(
    "E2E_RELAXED_RATE_LIMITS must never be set in production — it widens sensitiveWriteRateLimit/frequentInteractionRateLimit for the e2e CI suite only."
  );
}

if (env.NODE_ENV === "production" && env.E2E_RELAXED_AUTH_RATE_LIMIT) {
  throw new Error(
    "E2E_RELAXED_AUTH_RATE_LIMIT must never be set in production — it widens authRateLimit for the server CI job's test suite only."
  );
}

// Google OAuth (Search Console) is considered "enabled" once its client credentials are set.
// If so, INTEGRATIONS_ENCRYPTION_KEY must be present and decode to exactly 32 bytes — otherwise
// every GSC connection attempt would fail at runtime with a 500 (see utils/encryption.ts and
// gscConnection.service.ts, which both re-check this lazily on each call). Fail at boot instead.
const googleOAuthConfigured = Boolean(
  env.GOOGLE_OAUTH_CLIENT_ID && env.GOOGLE_OAUTH_CLIENT_SECRET && env.GOOGLE_OAUTH_REDIRECT_URI
);
if (googleOAuthConfigured) {
  if (!env.INTEGRATIONS_ENCRYPTION_KEY) {
    throw new Error(
      "GOOGLE_OAUTH_CLIENT_ID/SECRET/REDIRECT_URI are set but INTEGRATIONS_ENCRYPTION_KEY is missing. " +
      "Set INTEGRATIONS_ENCRYPTION_KEY (32 bytes, base64 or hex) before starting the server."
    );
  }
  const raw = env.INTEGRATIONS_ENCRYPTION_KEY;
  const keyLength = /^[0-9a-fA-F]{64}$/.test(raw)
    ? Buffer.from(raw, "hex").length
    : Buffer.from(raw, "base64").length;
  if (keyLength !== 32) {
    throw new Error(
      "INTEGRATIONS_ENCRYPTION_KEY must decode to exactly 32 bytes (base64 or hex) — Google OAuth is configured, so this key is required."
    );
  }
}

// n8n webhooks: both URL and secret must be set together, or neither. A base URL without a
// secret would let anyone who guesses the endpoint trigger production workflows unauthenticated.
if (Boolean(env.N8N_WEBHOOK_BASE_URL) !== Boolean(env.N8N_WEBHOOK_SECRET)) {
  throw new Error(
    "N8N_WEBHOOK_BASE_URL and N8N_WEBHOOK_SECRET must both be set, or both left unset."
  );
}
