export const queueNames = {
  communication: "communication",
  maintenance: "maintenance",
  documents: "documents",
} as const;

export const jobNames = {
  sendNotification: "send-notification",
  sendEmail: "send-email",
  cleanupRefreshTokens: "cleanup-refresh-tokens",
  archiveColdData: "archive-cold-data",
  warmDashboardSummaries: "warm-dashboard-summaries",
  recalculateClientScores: "recalculate-client-scores",
  expireProposals: "expire-proposals",
  markOverdueInvoices: "mark-overdue-invoices",
  checkStaleProjects: "check-stale-projects",
  checkOverdueDeadlines: "check-overdue-deadlines",
  checkInvoiceFollowup: "check-invoice-followup",
  weeklyCeoReport: "weekly-ceo-report",
  checkTaskDeadlines: "check-task-deadlines",
  checkOverdueTasks: "check-overdue-tasks",
  checkMeetingReminders: "check-meeting-reminders",
  generateDocument: "generate-document",
  syncSearchConsole: "sync-search-console",
  pruneAnalyticsEvents: "prune-analytics-events",
  checkStaleLeads: "check-stale-leads",
  checkPendingCommissions: "check-pending-commissions",
  closeStaleUserSessions: "close-stale-user-sessions",
  checkCustomQuestionSla: "check-custom-question-sla",
  checkApprovalSla: "check-approval-sla",
  weeklyHealthBoardDigest: "weekly-health-board-digest",
} as const;
